(() => {
'use strict';
const root=document.createElement('div');root.id='assistant-root';
root.innerHTML=`<div id="assistant-nudge" hidden>Опишите задачу — помогу найти инструмент.</div><button id="assistant-launcher" aria-label="Открыть помощника Орбиты" aria-expanded="false" aria-controls="assistant-panel" title="Спросить Орбиту"><span aria-hidden="true">✧</span></button><section id="assistant-panel" role="dialog" aria-label="Помощник Орбиты" hidden><header class="assistant-header"><span class="assistant-avatar" aria-hidden="true">✧</span><div><strong>Помощник Орбиты</strong><span class="assistant-status">● Локальный · без внешних AI</span></div><button id="assistant-close" aria-label="Закрыть помощника">×</button></header><div id="assistant-context"></div><div id="assistant-log" role="log" aria-live="polite" aria-relevant="additions" aria-label="История беседы" tabindex="0"></div><div id="assistant-quick" aria-label="Быстрые вопросы"></div><form id="assistant-form"><label class="sr-only" for="assistant-input">Сообщение помощнику</label><textarea id="assistant-input" rows="2" maxlength="1000" placeholder="Что нужно посчитать?"></textarea><button id="assistant-send" type="submit" aria-label="Отправить сообщение">↑</button></form><div class="assistant-footnote">Локальные правила, не нейросеть · Enter — отправить</div></section>`;
document.body.append(root);
const $=id=>document.getElementById(id),panel=$('assistant-panel'),launcher=$('assistant-launcher'),input=$('assistant-input'),log=$('assistant-log');
let enginePromise=null,engine=null,busy=false,opened=false,previousFocus=null,closeTimer;
const pageSections=()=>document.querySelectorAll('body > header, body > main, body > footer');
function modalState(){const modal=!panel.hidden&&innerWidth<=600;panel.setAttribute('aria-modal',String(modal));pageSections().forEach(el=>{el.inert=modal;});}
// Session state remains in DOM when closed; no conversation or input is sent anywhere.
function loadEngine(){if(!enginePromise)enginePromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='assistant-engine.js';s.onload=()=>resolve(new LocalAssistantEngine(Orbita.tools,Calc));s.onerror=()=>{s.remove();enginePromise=null;reject(Error('Не удалось загрузить помощника. Попробуйте открыть его ещё раз.'));};document.head.append(s);});return enginePromise;}
function message(role,text,actions=[]){const bubble=document.createElement('div');bubble.className='assistant-message '+role;const content=document.createElement('p');content.textContent=text;bubble.append(content);if(actions.length){const list=document.createElement('div');list.className='assistant-actions';actions.forEach(action=>{if(action.type!=='openTool'||!Orbita.tools.some(t=>t.id===action.toolId))return;const button=document.createElement('button');button.textContent=action.label;button.onclick=()=>{Orbita.openTool(action.toolId);close(false);};list.append(button);});bubble.append(list);}log.append(bubble);while(log.children.length>80)log.firstElementChild.remove();log.scrollTop=log.scrollHeight;}
function updateContext(){const c=Orbita.getContext();$('assistant-context').textContent=c.tool?'Сейчас: '+c.tool.name:'Сейчас: каталог инструментов';const questions=c.tool?c.tool.suggestedQuestions:['Подобрать калькулятор','Финансы','18% от 750'];$('assistant-quick').replaceChildren();questions.forEach(q=>{const b=document.createElement('button');b.type='button';b.textContent=q;b.disabled=busy;b.onclick=()=>send(q);$('assistant-quick').append(b);});}
function viewport(){const v=window.visualViewport;panel.style.setProperty('--assistant-height',Math.max(120,(v?.height||innerHeight)-24)+'px');panel.style.setProperty('--assistant-top',(v?.offsetTop||0)+12+'px');}
async function open(){clearTimeout(closeTimer);panel.classList.remove('closing');previousFocus=document.activeElement;panel.hidden=false;launcher.hidden=true;launcher.setAttribute('aria-expanded','true');$('assistant-nudge').hidden=true;viewport();modalState();updateContext();input.focus();if(!opened){message('bot','Привет! Помогу найти калькулятор, разобраться с расчётом и объяснить результат. Работаю локально по правилам — без внешних нейросетей.');opened=true;}try{engine=await loadEngine();}catch(e){message('bot',e.message);}}
function close(restore=true){panel.classList.add('closing');launcher.hidden=false;launcher.setAttribute('aria-expanded','false');pageSections().forEach(el=>{el.inert=false;});closeTimer=setTimeout(()=>{panel.hidden=true;panel.classList.remove('closing');},120);if(restore)(previousFocus?.isConnected?previousFocus:launcher).focus();}

async function send(raw){const text=raw.trim();if(!text||busy)return;const context=Orbita.getContext();busy=true;input.value='';message('user',text);$('assistant-send').disabled=true;updateContext();const thinking=document.createElement('div');thinking.className='assistant-thinking';thinking.textContent='Разбираю запрос…';log.append(thinking);log.setAttribute('aria-busy','true');try{engine=engine||await loadEngine();const answer=await engine.respond(text,context);thinking.remove();message('bot',answer.text,answer.actions);}catch{thinking.remove();message('bot','Не удалось обработать запрос. Попробуйте ещё раз.');}finally{busy=false;log.removeAttribute('aria-busy');$('assistant-send').disabled=false;updateContext();if(!panel.hidden)input.focus();}}
launcher.onclick=open;$('assistant-close').onclick=()=>close();$('assistant-form').onsubmit=e=>{e.preventDefault();send(input.value);};
panel.addEventListener('keydown',e=>{if(e.key==='Tab'&&innerWidth<=600){const elements=[...panel.querySelectorAll('button:not(:disabled),textarea,[tabindex="0"]')];const first=elements[0],last=elements.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}if(e.key==='Escape'){e.preventDefault();e.stopPropagation();close();}if(e.target===input&&e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();e.stopPropagation();send(input.value);}});
window.addEventListener('hashchange',()=>{if(!panel.hidden)updateContext();});
window.visualViewport?.addEventListener('resize',viewport);window.visualViewport?.addEventListener('scroll',viewport);window.addEventListener('resize',()=>{viewport();modalState();});
// One dismissible hint per tab session, never while the chat is open.
let hinted=false;try{hinted=sessionStorage.getItem('orbita-assistant-hint')==='1';}catch{}
if(!hinted)setTimeout(()=>{if(opened||document.hidden)return;$('assistant-nudge').hidden=false;try{sessionStorage.setItem('orbita-assistant-hint','1');}catch{}setTimeout(()=>{$('assistant-nudge').hidden=true;},6500);},7000);
})();
